#!/bin/bash
# Save context message and restart bot

MESSAGE="$1"

if [ -z "$MESSAGE" ]; then
  echo "Usage: ./save-and-restart.sh \"context message\""
  exit 1
fi

TIMESTAMP=$(date +%Y%m%d-%H%M%S)
SAVE_FILE="docs/tasks/save/restart-context-${TIMESTAMP}.md"

mkdir -p docs/tasks/save

# Use printf to safely write content without shell injection
printf '%s\n' "# Restart Context - $(date '+%Y-%m-%d %H:%M:%S %Z')" > "$SAVE_FILE"
printf '%s\n' "" >> "$SAVE_FILE"
printf '%s\n' "## Message from Previous Session" >> "$SAVE_FILE"
printf '%s\n' "" >> "$SAVE_FILE"
printf '%s\n' "$MESSAGE" >> "$SAVE_FILE"
printf '%s\n' "" >> "$SAVE_FILE"
printf '%s\n' "---" >> "$SAVE_FILE"
printf '%s\n' "*Auto-generated by save-and-restart.sh*" >> "$SAVE_FILE"

echo "✅ Context saved to $SAVE_FILE"
echo "🔄 Running make up..."

make up
